name: product_crud_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project for product crud
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  equatable: 2.0.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  get_it: 7.2.0
  fluttertoast: 8.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

