name: product_crud_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project for product crud
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  equatable: 2.0.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  get_it: 7.2.0
  fluttertoast: 8.1.1
  flutter_form_builder: 7.7.0
  form_builder_validators: 8.3.0
  bloc: 8.1.0
  flutter_bloc: 8.1.1
  mockito: 5.3.2
  bloc_test: any
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: any
  flutter_lints: ^2.0.0
  hive_generator: any
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

